// ============================================================
// Varsayılan Katsayılar — Kaynaklı
// Al-Hamrani et al. (2021), IEA (2018), Ecoinvent v3.6
// ============================================================

import type { Coefficient } from './schema';
import { getApprovedEmissionBenchmark } from './materialData';

function approvedMaterialEmission(materialId: string) {
  const benchmark = getApprovedEmissionBenchmark(materialId);
  if (!benchmark) throw new Error(`Onaylı malzeme emisyon benchmarkı bulunamadı: ${materialId}`);
  return benchmark;
}

export const DEFAULT_COEFFICIENTS: Coefficient[] = [
  // ── Ekskavatör ────────────────────────────────────────
  {
    key: 'FE_eksk',
    symbol: 'FE_eksk',
    value: 32.52,
    unit: 'L/h',
    source: 'Al-Hamrani et al. (2021), Table 3 — Hammer excavator',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Ekskavatör saatlik yakıt tüketimi',
    isEditable: true,
    category: 'excavator',
  },
  {
    key: 'ER',
    symbol: 'ER',
    value: 6,
    unit: 'm³/h',
    source: 'Al-Hamrani et al. (2021) — Excavation rate, orta sertlik zemin',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Ekskavatör kazı hızı (tek makine, C2 zemin)',
    isEditable: true,
    category: 'excavator',
  },

  // ── Damperli Kamyon ───────────────────────────────────
  {
    key: 'FE_damper',
    symbol: 'FE_damper',
    value: 0.368,
    unit: 'L/km',
    source: 'Al-Hamrani et al. (2021), Table 3 — Tipper truck',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Damperli kamyon ortalama yakıt tüketimi (yüklü/boş ortalaması)',
    isEditable: true,
    category: 'dumper_truck',
  },
  {
    key: 'CAP_damper',
    symbol: 'CAP_damper',
    value: 22,
    unit: 'm³',
    source: 'Al-Hamrani et al. (2021)',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Damperli kamyon kasa kapasitesi',
    isEditable: true,
    category: 'dumper_truck',
  },

  // ── Donatı Tırı ───────────────────────────────────────
  {
    key: 'FE_tir_yuklu',
    symbol: 'FE_tır_yüklü',
    value: 0.35,
    unit: 'L/km',
    source: 'Standart karayolu nakliyesi literatürü (IFEU/ECOTRANSIT referansı)',
    sourceType: 'literature',
    reliability: 'medium',
    description: 'Tır yüklü seyahat yakıt tüketimi',
    isEditable: true,
    category: 'rebar_truck',
  },
  {
    key: 'FE_tir_bos',
    symbol: 'FE_tır_boş',
    value: 0.28,
    unit: 'L/km',
    source: 'Standart karayolu nakliyesi literatürü (IFEU/ECOTRANSIT referansı)',
    sourceType: 'literature',
    reliability: 'medium',
    description: 'Tır boş dönüş yakıt tüketimi',
    isEditable: true,
    category: 'rebar_truck',
  },
  {
    key: 'CAP_tir',
    symbol: 'CAP_tır',
    value: 20,
    unit: 'ton',
    source: 'Varsayılan — kullanıcı değiştirebilir',
    sourceType: 'assumption',
    reliability: 'low',
    description: 'Tır yük kapasitesi',
    isEditable: true,
    category: 'rebar_truck',
  },

  // ── Beton Mikseri ─────────────────────────────────────
  {
    key: 'CAP_mixer',
    symbol: 'CAP_mixer',
    value: 8,
    unit: 'm³',
    source: 'Al-Hamrani et al. (2021)',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton mikseri kapasitesi',
    isEditable: true,
    category: 'concrete_mixer',
  },
  {
    key: 'FE_mixer_bos',
    symbol: 'FE_mixer_boş',
    value: 0.714,
    unit: 'L/km',
    source: 'Al-Hamrani et al. (2021), Table 3 — Concrete mixer empty',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton mikseri boş seyahat yakıt tüketimi',
    isEditable: true,
    category: 'concrete_mixer',
  },
  {
    key: 'FE_mixer_yuklu',
    symbol: 'FE_mixer_yüklü',
    value: 0.84,
    unit: 'L/km',
    source: 'Al-Hamrani et al. (2021), Table 3 — Concrete mixer loaded',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton mikseri yüklü seyahat yakıt tüketimi',
    isEditable: true,
    category: 'concrete_mixer',
  },
  {
    key: 'FE_mixer_rol',
    symbol: 'FE_mixer_röl',
    value: 11.13,
    unit: 'L/h',
    source: 'Al-Hamrani et al. (2021), Table 3 — Concrete mixer idle',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton mikseri rölanti yakıt tüketimi (bekleme)',
    isEditable: true,
    category: 'concrete_mixer',
  },
  {
    key: 'DR',
    symbol: 'DR',
    value: 2,
    unit: 'm³/dak',
    source: 'Al-Hamrani et al. (2021) — Discharging rate',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton boşaltma hızı',
    isEditable: true,
    category: 'concrete_mixer',
  },
  {
    key: 't_temiz_mixer',
    symbol: 't_temiz_mixer',
    value: 5,
    unit: 'dak/sefer',
    source: 'Al-Hamrani et al. (2021) — Cleaning time ≥5 min',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Mikser temizlik süresi (sefer başına)',
    isEditable: true,
    category: 'concrete_mixer',
  },

  // ── Beton Pompası ─────────────────────────────────────
  {
    key: 'FE_pompa_yol',
    symbol: 'FE_pompa_yol',
    value: 0.3,
    unit: 'L/km',
    source: 'Al-Hamrani et al. (2021), Table 3 — Concrete pump travel',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton pompası seyahat yakıt tüketimi',
    isEditable: true,
    category: 'concrete_pump',
  },
  {
    key: 'FE_pompa_cal',
    symbol: 'FE_pompa_çal',
    value: 26.6,
    unit: 'L/h',
    source: 'Al-Hamrani et al. (2021), Table 3 — Concrete pump working',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton pompası çalışma yakıt tüketimi',
    isEditable: true,
    category: 'concrete_pump',
  },
  {
    key: 'PR',
    symbol: 'PR',
    value: 38,
    unit: 'm³/h',
    source: 'Al-Hamrani et al. (2021) — Pumping rate',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Beton pompalama hızı',
    isEditable: true,
    category: 'concrete_pump',
  },
  {
    key: 't_vardiya',
    symbol: 't_vardiya',
    value: 8,
    unit: 'saat/gün',
    source: 'Al-Hamrani et al. (2021)',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Günlük çalışma vardiyası',
    isEditable: true,
    category: 'concrete_pump',
  },
  {
    key: 't_temiz_pompa',
    symbol: 't_temiz_pompa',
    value: 10,
    unit: 'dak/gün',
    source: 'Al-Hamrani et al. (2021) — Cleaning time ≥12 min (pompa)',
    sourceType: 'literature',
    reliability: 'high',
    description: 'Pompa temizlik süresi (gün başına)',
    isEditable: true,
    category: 'concrete_pump',
  },

  // ── Kompaktör ─────────────────────────────────────────
  {
    key: 'FE_kompak',
    symbol: 'FE_kompak',
    value: 18,
    unit: 'L/h',
    source: 'Genel inşaat makineleri literatürü',
    sourceType: 'literature',
    reliability: 'medium',
    description: 'Kompaktör (titreşimli silindir) yakıt tüketimi',
    isEditable: true,
    category: 'compactor',
  },
  {
    key: 'KR',
    symbol: 'KR',
    value: 150,
    unit: 'm²/h',
    source: 'Genel inşaat makineleri literatürü',
    sourceType: 'literature',
    reliability: 'medium',
    description: 'Kompaktör sıkıştırma hızı',
    isEditable: true,
    category: 'compactor',
  },
  {
    key: 'h_katman',
    symbol: 'h_katman',
    value: 0.3,
    unit: 'm',
    source: 'Standart uygulama',
    sourceType: 'standard',
    reliability: 'medium',
    description: 'Dolgu sıkıştırma katman kalınlığı',
    isEditable: true,
    category: 'compactor',
  },
  {
    key: 'N_gecis',
    symbol: 'N_geçiş',
    value: 4,
    unit: '—',
    source: 'Standart uygulama',
    sourceType: 'standard',
    reliability: 'medium',
    description: 'Katman başına kompaktör geçiş sayısı',
    isEditable: true,
    category: 'compactor',
  },

  // ── Emisyon Faktörü ───────────────────────────────────
  {
    key: 'EF_dizel',
    symbol: 'EF_dizel',
    value: 2.7,
    unit: 'kg CO₂-eq/L',
    source: 'IEA (2018) — Eq.(1): 2.69 + (0.0239×25)/1000 + (0.0074×298)/1000 ≈ 2.7',
    sourceType: 'standard',
    reliability: 'high',
    description:
      'Dizel yakıt emisyon faktörü (CO₂ + CH₄×GWP + N₂O×GWP). Yan et al. (2010) formülasyonu.',
    isEditable: true,
    category: 'emission_factor',
  },

  // ── Malzeme Üretim Emisyon Faktörleri ─────────────────
  {
    key: 'EF_cement',
    symbol: 'EF_çimento',
    value: approvedMaterialEmission('cement').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('cement').source,
    region: approvedMaterialEmission('cement').region,
    year: approvedMaterialEmission('cement').year,
    notes: approvedMaterialEmission('cement').notes,
    sourceType: 'literature',
    reliability: 'high',
    description: 'Portland çimento üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_coarse_aggregate',
    symbol: 'EF_iri_agrega',
    value: approvedMaterialEmission('natural_coarse_aggregate').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('natural_coarse_aggregate').source,
    region: approvedMaterialEmission('natural_coarse_aggregate').region,
    year: approvedMaterialEmission('natural_coarse_aggregate').year,
    notes: approvedMaterialEmission('natural_coarse_aggregate').notes,
    sourceType: 'literature',
    reliability: 'high',
    description: 'İri agrega üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_fine_aggregate',
    symbol: 'EF_ince_agrega',
    value: approvedMaterialEmission('natural_fine_aggregate').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('natural_fine_aggregate').source,
    region: approvedMaterialEmission('natural_fine_aggregate').region,
    year: approvedMaterialEmission('natural_fine_aggregate').year,
    notes: approvedMaterialEmission('natural_fine_aggregate').notes,
    sourceType: 'literature',
    reliability: 'high',
    description: 'İnce agrega (kum) üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_fly_ash',
    symbol: 'EF_uçucu_kül',
    value: approvedMaterialEmission('fly_ash').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('fly_ash').source,
    region: approvedMaterialEmission('fly_ash').region,
    year: approvedMaterialEmission('fly_ash').year,
    notes: approvedMaterialEmission('fly_ash').notes,
    sourceType: 'literature',
    reliability: 'high',
    description: 'Uçucu kül malzeme üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_ggbfs',
    symbol: 'EF_GGBFS',
    value: approvedMaterialEmission('slag').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('slag').source,
    region: approvedMaterialEmission('slag').region,
    year: approvedMaterialEmission('slag').year,
    notes: approvedMaterialEmission('slag').notes,
    sourceType: 'literature',
    reliability: 'high',
    description: 'GGBFS/cüruf malzeme üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_silica_fume',
    symbol: 'EF_silis_dumanı',
    value: approvedMaterialEmission('silica_fume').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('silica_fume').source,
    region: approvedMaterialEmission('silica_fume').region,
    year: approvedMaterialEmission('silica_fume').year,
    notes: approvedMaterialEmission('silica_fume').notes,
    sourceType: 'literature',
    reliability: 'high',
    description: 'Silis dumanı malzeme üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_metakaolin',
    symbol: 'EF_metakaolin',
    value: approvedMaterialEmission('metakaolin').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('metakaolin').source,
    region: approvedMaterialEmission('metakaolin').region,
    year: approvedMaterialEmission('metakaolin').year,
    notes: approvedMaterialEmission('metakaolin').notes,
    sourceType: 'literature',
    reliability: 'medium',
    description: 'Metakaolin malzeme üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_water',
    symbol: 'EF_su',
    value: approvedMaterialEmission('water').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('water').source,
    region: approvedMaterialEmission('water').region,
    year: approvedMaterialEmission('water').year,
    notes: approvedMaterialEmission('water').notes,
    sourceType: 'assumption',
    reliability: 'medium',
    description: 'Karışım suyu emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_superplasticizer',
    symbol: 'EF_süperakışkanlaştırıcı',
    value: approvedMaterialEmission('superplasticizer').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('superplasticizer').source,
    region: approvedMaterialEmission('superplasticizer').region,
    year: approvedMaterialEmission('superplasticizer').year,
    notes: approvedMaterialEmission('superplasticizer').notes,
    sourceType: 'literature',
    reliability: 'high',
    description: 'Süperakışkanlaştırıcı / su azaltıcı emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_recycled_aggregate',
    symbol: 'EF_RCA',
    value: approvedMaterialEmission('recycled_coarse_aggregate').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('recycled_coarse_aggregate').source,
    region: approvedMaterialEmission('recycled_coarse_aggregate').region,
    year: approvedMaterialEmission('recycled_coarse_aggregate').year,
    notes: `${approvedMaterialEmission('recycled_coarse_aggregate').notes} Belirsizlik aralığı 0.004-0.012 kg CO₂-eq/kg.`,
    sourceType: 'assumption',
    reliability: 'low',
    description: 'Geri dönüştürülmüş beton agregası merkez emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_steel',
    symbol: 'EF_çelik',
    value: approvedMaterialEmission('reinforcement_steel').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('reinforcement_steel').source,
    region: approvedMaterialEmission('reinforcement_steel').region,
    year: approvedMaterialEmission('reinforcement_steel').year,
    notes: approvedMaterialEmission('reinforcement_steel').notes,
    sourceType: 'literature',
    reliability: 'medium',
    description: 'Donatı çeliği üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_air_entraining',
    symbol: 'EF_hava_sürükleyici',
    value: 0.4393,
    unit: 'kg CO₂-eq/kg',
    source: 'EFCA / IBU Model EPD · Concrete admixtures – Air entrainers · EPD-EFC-20210193-IBG1-EN',
    sourceType: 'literature',
    sourceUrl: 'https://ibudata.lca-data.com/datasetdetail/process.xhtml?uuid=3063f481-9b3c-425c-92dc-d7f6608cd90b&version=00.01.000',
    region: 'Europe',
    year: 2021,
    notes: 'A1-A3 GWP-total, 1 kg beyan birimi. Model EPD en yüksek etkili ürün senaryosunu kullanır; veri seti 2026 sonuna kadar geçerlidir.',
    reliability: 'high',
    description: 'Hava sürükleyici beton katkısı üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
  {
    key: 'EF_sodium_hydroxide',
    symbol: 'EF_NaOH',
    value: approvedMaterialEmission('sodium_hydroxide').value,
    unit: 'kg CO₂-eq/kg',
    source: approvedMaterialEmission('sodium_hydroxide').source,
    region: approvedMaterialEmission('sodium_hydroxide').region,
    year: approvedMaterialEmission('sodium_hydroxide').year,
    notes: approvedMaterialEmission('sodium_hydroxide').notes,
    sourceType: 'assumption',
    reliability: 'low',
    description: 'Sodyum hidroksit (NaOH) üretim emisyon faktörü',
    isEditable: true,
    category: 'material_emission',
  },
];

export const MATERIAL_EMISSION_COEFFICIENT_KEYS: Readonly<Record<string, string>> = {
  cement: 'EF_cement',
  fly_ash: 'EF_fly_ash',
  slag: 'EF_ggbfs',
  silica_fume: 'EF_silica_fume',
  metakaolin: 'EF_metakaolin',
  natural_coarse_aggregate: 'EF_coarse_aggregate',
  natural_fine_aggregate: 'EF_fine_aggregate',
  recycled_coarse_aggregate: 'EF_recycled_aggregate',
  recycled_fine_aggregate: 'EF_recycled_aggregate',
  recycled_aggregate_unspecified: 'EF_recycled_aggregate',
  water: 'EF_water',
  superplasticizer: 'EF_superplasticizer',
  air_entraining: 'EF_air_entraining',
  sodium_hydroxide: 'EF_sodium_hydroxide',
  reinforcement_steel: 'EF_steel',
};

export function getMaterialEmissionCoefficient(materialId: string): Coefficient | undefined {
  const key = MATERIAL_EMISSION_COEFFICIENT_KEYS[materialId];
  return key ? getCoefficient(key) : undefined;
}

/**
 * Key bazlı hızlı erişim için coefficient map oluşturur.
 */
export function getCoefficientMap(): Map<string, Coefficient> {
  const map = new Map<string, Coefficient>();
  for (const coeff of DEFAULT_COEFFICIENTS) {
    map.set(coeff.key, coeff);
  }
  return map;
}

/**
 * Belirli bir katsayıyı key ile getir.
 */
export function getCoefficient(key: string): Coefficient | undefined {
  return DEFAULT_COEFFICIENTS.find((c) => c.key === key);
}

/**
 * Katsayı değerini getir. Özelleştirilmiş değer varsa onu, yoksa varsayılanı döner.
 */
export function getCoefficientValue(
  key: string,
  customValues?: Map<string, number>
): number {
  if (customValues?.has(key)) {
    return customValues.get(key)!;
  }
  const coeff = getCoefficient(key);
  if (!coeff) throw new Error(`Bilinmeyen katsayı: ${key}`);
  return coeff.value;
}
