import type { MaterialPrice } from './types';
import { getApprovedMaterialPrice } from '../coefficients/materialData';

const DEFAULT_PRICE_DATE = '2026-09-06';

const OFFICIAL_NOTE = 'Referans çıplak malzeme rayicidir; KDV, proje özelindeki nakliye ve tedarikçi iskonto/farkları ayrıca değerlendirilmelidir.';
const MARKET_NOTE = 'Türkiye için piyasa referansıdır; gerçek satın alma fiyatı miktar, bölge, kalite ve teslim şekline göre değişebilir. Kullanıcı teklifiyle değiştirilebilir.';
const FALLBACK_NOTE = 'Kategori bazlı yaklaşık varsayılandır. Özel/kullanıcı tanımlı malzemede gerçek tedarikçi teklifi girilmesi önerilir.';

const DEFAULT_MATERIAL_PRICES: Record<string, MaterialPrice> = {
  cement: {
    value: 2878.64,
    unit: 'TL/ton',
    currency: 'TRY',
    date: '2026-05-01',
    source: 'AYGM 2026 Mayıs rayiçleri · 10.130.1202 Portland çimentosu (dökme, CEM I 42,5 N)',
    sourceUrl: 'https://aygm.uab.gov.tr/uploads/pages/birim-fiyatlar/2026-yili-mayis-ayi-liman-ve-deniz-insaati-islerine-ait-rayicler.pdf',
    region: 'Türkiye',
    year: 2026,
    notes: OFFICIAL_NOTE,
  },
  natural_fine_aggregate: {
    value: 414.15,
    unit: 'TL/m³',
    currency: 'TRY',
    date: '2026-09-01',
    source: 'ÇŞİDB 2026 Eylül rayici · 10.130.1006 hazırlanmış kum (İmarX derlemesi)',
    sourceUrl: 'https://imarx.com.tr/kesif/poz.php?no=10.130.1006',
    region: 'Türkiye',
    year: 2026,
    notes: OFFICIAL_NOTE,
  },
  natural_coarse_aggregate: {
    value: 606.25,
    unit: 'TL/m³',
    currency: 'TRY',
    date: '2026-05-01',
    source: "AYGM 2026 Mayıs rayiçleri · 10.130.1029 32 mm'ye kadar kırmataş",
    sourceUrl: 'https://aygm.uab.gov.tr/uploads/pages/birim-fiyatlar/2026-yili-mayis-ayi-liman-ve-deniz-insaati-islerine-ait-rayicler.pdf',
    region: 'Türkiye',
    year: 2026,
    notes: OFFICIAL_NOTE,
  },
  custom_aggregate: {
    value: 300,
    unit: 'TL/ton',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Kullanıcı tanımlı agrega için kategori bazlı varsayılan',
    region: 'Türkiye',
    year: 2026,
    notes: FALLBACK_NOTE,
  },
  lightweight_aggregate: {
    value: 2500,
    unit: 'TL/ton',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Hafif agrega için kategori bazlı Türkiye piyasa varsayımı',
    region: 'Türkiye',
    year: 2026,
    notes: 'Pomza, perlit, genleştirilmiş kil vb. ürünlerde fiyat çok değişkendir; maliyetin boş kalmaması için başlangıç değeri sağlanır ve tedarikçi teklifiyle değiştirilmelidir.',
  },
  heavyweight_aggregate: {
    value: 4000,
    unit: 'TL/ton',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Ağır agrega için kategori bazlı Türkiye piyasa varsayımı',
    region: 'Türkiye',
    year: 2026,
    notes: 'Barit, hematit/manyetit vb. ağır agregalarda cevher kalitesi ve lojistik fiyatı belirleyicidir; tedarikçi teklifiyle değiştirilmelidir.',
  },
  other_binder: {
    value: 5000,
    unit: 'TL/ton',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Diğer bağlayıcı/puzolan için kategori bazlı varsayılan',
    region: 'Türkiye',
    year: 2026,
    notes: FALLBACK_NOTE,
  },
  other_pozzolanic: {
    value: 5000,
    unit: 'TL/ton',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Diğer bağlayıcı/puzolan için kategori bazlı varsayılan',
    region: 'Türkiye',
    year: 2026,
    notes: FALLBACK_NOTE,
  },
  water: {
    value: 64.76,
    unit: 'TL/m³',
    currency: 'TRY',
    date: '2026-09-01',
    source: 'ÇŞİDB 2026 Eylül rayici · 10.130.9991 su (İmarX derlemesi)',
    sourceUrl: 'https://imarx.com.tr/kesif/poz.php?no=10.130.9991',
    region: 'Türkiye',
    year: 2026,
    notes: OFFICIAL_NOTE,
  },
  superplasticizer: {
    value: 191.42,
    unit: 'TL/kg',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'MyFix Ocak 2026 · MFS-637 IBC/kg 3,40 €; ECB 04.09.2026 EUR/TRY referansı ile dönüştürüldü',
    sourceUrl: 'https://www.myfixyapikim.com/content/files/2026/1/files-F4A1fxECeuihCsmCrRKP.pdf',
    region: 'Türkiye',
    year: 2026,
    notes: '3,40 €/kg × 56,2995 TRY/EUR = yaklaşık 191,42 TL/kg. Ürün konsantrasyonu ve toplu alım iskontosu fiyatı önemli ölçüde değiştirebilir.',
  },
  air_entraining: {
    value: 54.2,
    unit: 'TL/kg',
    currency: 'TRY',
    date: '2026-08-01',
    source: 'ÇŞİDB 2026 Ağustos rayici · 10.300.2038 hava sürükleyici kimyasal katkı (İmarX derlemesi)',
    sourceUrl: 'https://imarx.com.tr/kesif/poz.php?no=10.300.2038',
    region: 'Türkiye',
    year: 2026,
    notes: OFFICIAL_NOTE,
  },
  accelerator: {
    value: 54.5,
    unit: 'TL/kg',
    currency: 'TRY',
    date: '2026-08-01',
    source: 'ÇŞİDB TS EN 934-2 kimyasal katkı rayiç bandına göre 2026 referansı',
    sourceUrl: 'https://webdosya.csb.gov.tr/db/yfk/icerikler/2025-yili-b-r-m-f-yatlari-1701251611-20250117141859.pdf',
    region: 'Türkiye',
    year: 2026,
    notes: '2025 resmi hızlandırıcı rayici 30 TL/kg; 2026 aynı kimyasal katkı grubundaki güncel 54,20–54,66 TL/kg bandı esas alınarak yaklaşık 54,50 TL/kg referanslanmıştır.',
  },
  retarder: {
    value: 54.66,
    unit: 'TL/kg',
    currency: 'TRY',
    date: '2026-07-01',
    source: 'ÇŞİDB 2026 Temmuz rayici · 10.300.2035 priz geciktirici kimyasal katkı (İmarX derlemesi)',
    sourceUrl: 'https://imarx.com.tr/kesif/poz.php?no=10.300.2035',
    region: 'Türkiye',
    year: 2026,
    notes: OFFICIAL_NOTE,
  },
  custom_admixture: {
    value: 55,
    unit: 'TL/kg',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'TS EN 934-2 kimyasal katkılar için kategori bazlı varsayılan',
    region: 'Türkiye',
    year: 2026,
    notes: FALLBACK_NOTE,
  },
  steel_fiber: {
    value: 85,
    unit: 'TL/kg',
    currency: 'TRY',
    date: '2025-11-01',
    source: 'Beton Elyafı · 0,75×60 mm tutkallı çelik fiber, 500 kg+ liste fiyatı',
    sourceUrl: 'https://www.betonelyafi.com/betona-tel.html',
    region: 'Türkiye',
    year: 2025,
    notes: MARKET_NOTE,
  },
  pp_fiber: {
    value: 388.89,
    unit: 'TL/kg',
    currency: 'TRY',
    date: '2026-09-01',
    source: 'Beton Malzemeleri · PP beton elyafı 900 g paket 350 TL',
    sourceUrl: 'https://www.betonmalzemeleri.com/cam-elyaf-fiyatlari.html',
    region: 'Türkiye',
    year: 2026,
    notes: '350 TL / 0,9 kg = yaklaşık 388,89 TL/kg; paket ve sipariş miktarına göre değişir.',
  },
  glass_fiber: {
    value: 50,
    unit: 'TL/kg',
    currency: 'TRY',
    date: '2026-09-01',
    source: 'Beton Malzemeleri · cam elyaf 12–18 mm, 2.000 kg+ depo teslim',
    sourceUrl: 'https://www.betonmalzemeleri.com/cam-elyaf-fiyatlari.html',
    region: 'Türkiye',
    year: 2026,
    notes: MARKET_NOTE,
  },
  other_fiber: {
    value: 100,
    unit: 'TL/kg',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Diğer fiber için kategori bazlı varsayılan',
    region: 'Türkiye',
    year: 2026,
    notes: FALLBACK_NOTE,
  },
  sodium_hydroxide: {
    value: 110,
    unit: 'TL/kg',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Türkiye e-ticaret toplu paket benchmarkı · %98–99 NaOH 25 kg yaklaşık 2.749 TL',
    sourceUrl: 'https://www.trendyol.com/sodyum-hidroksit-y-s13480',
    region: 'Türkiye',
    year: 2026,
    notes: '25 kg paket benchmarkı yaklaşık 109,96 TL/kg. Endüstriyel tanker/tonaj alımlarında daha düşük fiyat görülebilir.',
  },
  sodium_silicate: {
    value: 67.5,
    unit: 'TL/kg',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Kimyacınız · sodyum silikat/cam suyu 30 kg paket 2.025 TL',
    sourceUrl: 'https://www.kimyaciniz.com/sodyum-silikat',
    region: 'Türkiye',
    year: 2026,
    notes: '30 kg paket satış fiyatından 67,50 TL/kg hesaplanmıştır.',
  },
  alkali_activator: {
    value: 82,
    unit: 'TL/kg',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'NaOH + sodyum silikat piyasa fiyatlarından türetilmiş aktivatör çözeltisi benchmarkı',
    region: 'Türkiye',
    year: 2026,
    notes: 'Yaklaşık 1/3 NaOH + 2/3 sodyum silikat kütle harmanı üzerinden referanslanmıştır. Gerçek molarite/modül ve su oranına göre kullanıcı güncellemelidir.',
  },
  custom_activator: {
    value: 82,
    unit: 'TL/kg',
    currency: 'TRY',
    date: DEFAULT_PRICE_DATE,
    source: 'Alkali aktivatör için kategori bazlı varsayılan',
    region: 'Türkiye',
    year: 2026,
    notes: FALLBACK_NOTE,
  },
};

function dynamicFallback(materialId: string): MaterialPrice | null {
  const prefix = materialId.split('-custom-')[0];
  const fallbackByPrefix: Record<string, MaterialPrice> = {
    binder: DEFAULT_MATERIAL_PRICES.other_binder,
    aggregate: DEFAULT_MATERIAL_PRICES.custom_aggregate,
    water: DEFAULT_MATERIAL_PRICES.water,
    admixture: DEFAULT_MATERIAL_PRICES.custom_admixture,
    fiber: DEFAULT_MATERIAL_PRICES.other_fiber,
    activator: DEFAULT_MATERIAL_PRICES.custom_activator,
  };
  const fallback = fallbackByPrefix[prefix];
  return fallback ? { ...fallback } : null;
}

export function getDefaultMaterialPrice(materialId: string): MaterialPrice | null {
  const approved = getApprovedMaterialPrice(materialId);
  if (approved) return approved;
  const price = DEFAULT_MATERIAL_PRICES[materialId] ?? dynamicFallback(materialId);
  return price ? { ...price } : null;
}

export function hasDefaultMaterialPrice(materialId: string): boolean {
  return getDefaultMaterialPrice(materialId) != null;
}
